#' @title Gather samples of predictions
#' @description Collapses the multi-label predictions across sets of classifier
#'   chains and iterations into a single set of predictions, either binary or
#'   probabilistic.
#' @param object A \code{pugs} object generated by \code{\link{predict.ECC}}.
#' @param ... \code{type = "prob"} for probabilistic predictions,
#' \code{type = "class"} for binary (0/1) predictions
#' @return A matrix of predictions.
#' @export
summary.PUGS <- function(object, ...)
{
  if (length(dim(object$preds)) != 4) {
    stop("object should contain an instances \u00d7 labels \u00d7 iterations \u00d7 models array")
  }
  type <- list(...)$type
  if ( is.null(type) ) {
    type <- "class"
  }
  if (!(type %in% c("class", "prob"))) {
    stop("type should be either 'class' or 'prob'")
  }
  if ( type == "class" ) {
    majority <- function(y) { return(1 * ((sum(y) / length(y)) > 0.5)) }
    output <- apply(apply(object$preds, c(1, 2, 4), majority), c(1, 2), majority)
  } else {
    output <- apply(apply(object$preds, c(1, 2, 4), function(y) { return(sum(y)/length(y)) } ), c(1, 2), mean)
  }
  colnames(output) <- object$y_labels
  return(output)
}
