#' Gather samples of predictions
#' 
#' @param object A \code{pugs} object generated by \code{\link{predict.ECC}}.
#' @param ... \code{type = "prob"} for probabilistic predictions,
#' \code{type = "class"} for binary (0/1) predictions
#' @return A matrix of predictions.
#' @examples \dontrun{
#'   y.pred <- ecc(x, y) %>% predict(x.new) %>% summary
#' }

#' @export
summary.PUGS <- function(object, ...)
{
  if (length(dim(object$preds)) != 4) stop("object should contain an instances \u00d7 labels \u00d7 iterations \u00d7 models array")
  type <- list(...)$type
  if ( is.null(type) ) type <- "class"
  if (!(type %in% c("class", "prob"))) stop("type should be either 'class' or 'prob'")
  if ( type == "class" ) {
    # majority <- . %>% table %>% { names(.)[which.max(.)] } %>% as.numeric
    majority <- function(y) 1*((sum(y)/length(y))>0.5)
    object$preds %>% apply(c(1, 2, 4), majority) %>%
      apply(c(1, 2), majority) %>%
      { colnames(.) <- object$y_labels; . } %>%
      return
  } else {
    object$preds %>% apply(c(1, 2, 4), function(y) sum(y)/length(y) ) %>%
      apply(c(1, 2), mean) %>%
      { colnames(.) <- object$y_labels; . } %>%
      return
  }
}
